//sqls package is autogenerated by gosql.
//Do not edit this file.
//Changes will be lost on next auto-generate.
package sqls

//Create new user.
//
//Fields: 2, Parameters: 2
//
//  Fields: name, age
//
//  ParamFields: name, age
//
//  ReturningFields: id
const UserCreate string = "insert into users(name, age) values($1, $2) returning id;"

//Gives list of question ID and Title only to fill dropdowns.
//
//Fields: 3, Parameters: 0
//
//  Fields: q.ID, qd.Title, rowcount
const QuesListForDD string = "select q.ID, qd.Title, count(*) over() as rowcount from questions q, questiondata qd where (q.ID=qd.QID and q.TopicID=21) order by qd.QID desc;"

